#!/usr/bin/php
<?php
/* 
    This file is part of phpautoconf.

    phpautoconf is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    phpautoconf is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
*/

if (!isset($argv[1]) || !$argv[1]) {
	echo "Usage: run.sh <conf_name>\n";
} else {
	$confName = $argv[1];
	$baseDir = dirname(__FILE__); 
	
	require_once($baseDir . '/lib/autoload/init.php');
	require_once($baseDir . "/conf/$confName/main.php");
	require_once($baseDir . '/lib/autoload/finalize.php');
}
?>
